version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: dataset of Circle data (French eco-responsible)
    tables:
      - name: product
        description: Product table
        identifier: raw_gz_product
      - name: sales
        description: Sales table
        identifier: raw_gz_sales  
      - name: ship
        description: Shipping table
        identifier: raw_gz_ship