version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per productid found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          # OR ## if dbt_utils is installed
          # - dbt_utils.unique_combination_of_columns:
          #     combination_of_columns:
          #       - orders_id
          #       - pdt_id

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:
          - name: orders_id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the distribution centre/warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier/logistics provider

      - name: adwords
        identifier: raw_gz_adwords
        description: Greenweez adwords data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: identifies adwords supplier
          - name: campaign_key
            description: campaign identifier 
          - name: camPGN_name
            description: campaign label
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks

      - name: bing
        identifier: raw_gz_bing
        description: Greenweez bing data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: identifies bing supplier
          - name: campaign_key
            description: campaign identifier 
          - name: camPGN_name
            description: campaign label
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks

      - name: criteo
        identifier: raw_gz_criteo
        description: Greenweez criteo data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: identifies criteo supplier
          - name: campaign_key
            description: campaign identifier 
          - name: camPGN_name
            description: campaign label
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks

      - name: facebook
        identifier: raw_gz_facebook
        description: Greenweez facebook data
        columns:
          - name: date_date
            description: campaign date
          - name: paid_source
            description: identifies facebook supplier
          - name: campaign_key
            description: campaign identifier 
          - name: camPGN_name
            description: campaign label
          - name: ads_cost
            description: cost of campaign
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks